#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apache2'
cookbook 'apt'
cookbook 'fail2ban'
cookbook 'git'
cookbook 'openssh'
cookbook 'percona',
  :path => File.expand_path("~/repos/chef-percona-phlipper")
  # Pending PR: https://github.com/phlipper/chef-percona/pull/68
  #:git => 'https://github.com/patcon/chef-percona',
  #:ref => '68-percona-server-recipe'
cookbook 'php'
cookbook 'proviso',
  :path => 'cookbooks-source/proviso'
cookbook 'vim'
cookbook 'yum',
  # Pending release: https://github.com/opscode-cookbooks/yum/pull/49
  :git => 'https://github.com/opscode-cookbooks/yum'
cookbook 'zsh'
